### ISSUE TITLE
RuntimeError: The size of tensor a (24) must match the size of tensor b (12) at non-singleton dimension 2

### ISSUE THREAD

**Issue by liuxz-cs** [YBYBZhang/ControlVideo#14]
When we run by `python inference.py --condition "depth" --video_length 24 --smoother_steps 19 20 --width 512 --height 512`, we get the error 
`
Traceback (most recent call last):
  File "/root/paddlejob/workspace/lxz/ControlVideo/inference.py", line 129, in <module>
    sample = pipe(args.prompt + POS_PROMPT, video_length=args.video_length, frames=pil_annotation, 
  File "/root/paddlejob/workspace/lxz/miniconda3/envs/controlvideo_py310/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/paddlejob/workspace/lxz/ControlVideo/models/pipeline_controlvideo.py", line 902, in __call__
    down_block_res_samples, mid_block_res_sample = self.controlnet(
  File "/root/paddlejob/workspace/lxz/miniconda3/envs/controlvideo_py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/paddlejob/workspace/lxz/ControlVideo/models/controlnet.py", line 519, in forward
    sample += controlnet_cond
RuntimeError: The size of tensor a (24) must match the size of tensor b (12) at non-singleton dimension 2
`
It seems that the depth detector extracts the depth of the size of channel b(12), but the video_length is 24, the size of a(24), so how can solve this problem?

**Comment by YBYBZhang** [comment]
Maybe the length of input video is 12, which is less than ``video_length``. Less ``video_length`` could address this problem.

**Comment by liuxz-cs** [comment]
> Maybe the length of input video is 12, which is less than `video_length`. Less `video_length` could address this problem.

I have solved this problem, because when read video by the function read_video() in models/utils.py, the frame_rate is default to be 2, but when we want to keep all frames of the input video, it may lead this problem. For example, the total number of the input video is 24, and we want to keep all this 24 frames, the frame_rate should not to be 2. I suggest that, you can set the frame_rate in this function read_video() to be `frame_rate = len(vr) // video_length`.  Then users do not need to modify the value of frame_rate manually to avoid mismatching of its value.

**Comment by YBYBZhang** [comment]
Thanks for your suggestion! I have added it to the code.
