### ISSUE TITLE
ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for fie  

### ISSUE THREAD

**Issue by KaiJia2017** [YBYBZhang/ControlVideo#20]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.11/site-packages/timm/__init__.py", line                                                                                                                    2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model                                                                                                                   _entrypoint, \
  File "/home/ubuntu/.local/lib/python3.11/site-packages/timm/models/__init__.py                                                                                                                   ", line 28, in <module>
    from .maxxvit import *
  File "/home/ubuntu/.local/lib/python3.11/site-packages/timm/models/maxxvit.py"                                                                                                                   , line 216, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1221, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1211, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 959, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 816, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for fie

**Comment by KaiJia2017** [comment]
python -m pip install timm==0.6.7
it work!
